spring:
  application:
    name: doc-analyzing
  datasource:
    url: jdbc:postgresql://localhost:5432/inspector_rag
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
