spring:
  application:
    name: embedding
  datasource:
    url: jdbc:postgresql://localhost:5432/inspector_rag
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info

inspector:
  embedding:
    model-name: ${EMBEDDING_MODEL_NAME:text-embedding-3-small}
    model-version: ${EMBEDDING_MODEL_VERSION:v1}
    dimension: ${EMBEDDING_MODEL_DIMENSION:1536}
