spring:
  application:
    name: records
  datasource:
    url: jdbc:postgresql://localhost:5432/inspector_rag
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info

inspector:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
